version: '3'
  
services:
    deadline-repo:
        container_name: DeadlineRepository10
        
        image: deadline-repository:10.1
        restart: unless-stopped
        
        volumes:
            - /opt/Thinkbox:/opt/Thinkbox
            - /etc/localtime:/etc/localtime:ro

        ports:
            - '27100:27100'
