version: '3'
  
services:
    deadline-repo:
        container_name: DeadlineRepository10
        
        image: deadline-repository:10.1
        restart: unless-stopped
        
        volumes:
            - type: bind
              source: /home/Thinkbox
              target: /opt/Thinkbox
        
        environment:
            TZ: "Asia/Shanghai"    

        ports:
            - '27100:27100'
